services:
  enterprise-api:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5001
      - ConnectionStrings__DefaultConnection=Server=enterprise-postgres;Database=enterprise_db;Username=enterprise_user;Password=enterprise_pass123
      - Redis__ConnectionString=enterprise-redis:6379
    depends_on:
      - enterprise-postgres
      - enterprise-redis
    restart: unless-stopped

  enterprise-postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=enterprise_db
      - POSTGRES_USER=enterprise_user
      - POSTGRES_PASSWORD=enterprise_pass123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  enterprise-redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
