version: '3.8'

services:
  # Web App (Frontend)
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
      - API_URL=http://api:3000
    depends_on:
      - api
    networks:
      - enterprise-network

  # API Server (Backend)
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    networks:
      - enterprise-network

networks:
  enterprise-network:
    driver: bridge
